# Used URI for internal items definition
URI = imss://

# Block size (in KB)
BLOCK_SIZE = 512

# Used mount point in the client side
MOUNT_POINT = /mnt/hercules/

# Path where the Hercules project is located
HERCULES_PATH = /beegfs/home/david.singh/hercules

# Port listening in the metadata node service
METADATA_PORT = 75000

# Port listening in the data node service
DATA_PORT =     85000

# Total number of data nodes
NUM_DATA_SERVERS = 1 

# Total number of metadadata nodes
NUM_META_SERVERS = 1

# Total number of client nodes
NUM_NODES_FOR_CLIENTS = 1

# Total number of clients per node
NUM_CLIENTS_PER_NODE = 1

# [1, 0]: Client process are share resources with data nodes
ATTACHED = 0

# [1, 0]: Enables malleability functions
MALLEABILITY = 0
UPPER_BOUND_MALLEABILITY = 0
LOWER_BOUND_MALLEABILITY = 0
INIT_NUM_DATA_SERVERS = 1

# File containing a list of nodes serving as data nodes
DATA_HOSTFILE = /beegfs/home/david.singh/EpiGraphFlexMPI/data_hostfile 

# Number of threads attending data requests
THREAD_POOL = 1

# Maximum size used by the data nodes
STORAGE_SIZE = 1 # No limit

# File containing a list of nodes serving as metadata nodes
METADATA_HOSTFILE = /beegfs/home/david.singh/EpiGraphFlexMPI/meta_hostfile

# Replication factor (1, 2 or 3)
REPL_FACTOR = 1

# [none, all]: Debug mode (none, SLOG_TIME, all)
DEBUG_LEVEL = none

# [RR, BUCKETS, HASH, CRC16b, CRC64b, LOCAL]: Distribution policy (RR by default)
POLICY = RR
