#!/bin/bash
## Last modification: 18/12/2023
# set -x
#######################################################
#######################################################
## To stop all servers.
StopServers() {
    NAME=$1
    hosts=$2
    WAIT_SERVERS=$3

    awk 'FNR==NR{a[$0]=NR;next}{print a[$0]}' data_hostfile data2stop_hostfile > data2stop_index
    readarray -t data2stop_index_arr < data2stop_index

    length=${#hosts[@]}
    reversed=()
    for (( i=$length-1; i>=0; i-- )); do
        reversed+=("${hosts[$i]}")
    done


    if [[ $NAME = "data" ]]; then
        for index in "${data2stop_index_arr[@]}"
        do
            FILE="./tmp/d-hercules-$((index-1))-down"
            if [ -f $FILE ]; then
                echo "Temporal file $FILE has been deleted"
                rm $FILE
            else 
                echo "Temporal file $FILE does not exist"
            fi
        done
    fi

    # echo "# Hercules: Stopping $NAME servers in $hosts"
    echo "# Hercules: Stopping $length $NAME servers in ${reversed[@]}"
    # i=0
    # for node in "${hosts[@]}"
    for node in "${reversed[@]}"
    do
        echo "ssh $node pkill hercules_server"
        # Move blocks from this server to another.
        # ( ssh $node "pkill -SIGUSR2 hercules_server" ) 
        # Kill threads and finish the server.
        ##  ( ssh $node "export NUMBER_ACTIVE_STORAGE_SERVERS=5" )
        ( ssh $node "pkill -SIGUSR1 hercules_server" )
        # i=$((i+1))
    done
    # WaitForServersDown "data" "d" "$i" ${reversed[@]}
    if [[ "$WAIT_SERVERS" -eq "1" ]]; then
        WaitForServersDown "data" "d" ${reversed[@]}
    else
        echo "No waiting for data servers to be finished."
    fi
}

## To wait until all the servers are down.
WaitForServersDown() {

    readarray -t data2stop_index_arr < data2stop_index

    SERVER_ID=0
    # get server name by arguments.
    SERVER_NAME=$1
    shift
    # get server type by arguments.
    SERVER_TYPE=$1
    shift
    # get server id by arguments.
    # SERVER_ID=$1
    # shift
    # get list of hostnames where to stop servers.
    hosts=("$@")
    # echo "hostnames=${hosts[@]}"
    ATTEMPS=1000
    for node in "${hosts[@]}"
    do
        # SERVER_ID=$i
        # COMMAND="$HERCULES_BASH_PATH/check-servers.sh $SERVER_TYPE $SERVER_ID down"
        # echo "[+] Running comprobation $SERVER_ID in $node... $COMMAND"
        # # if slurm is not available.
        # if [[ "$SLURM" -eq "0" ]]; then
        #     if [ -z "$(ssh-keygen -F $node)" ]; then
        #         ssh-keyscan -H $node >> ~/.ssh/known_hosts
        #     fi
        #     ssh $node "$COMMAND"
        # else # if slurm is available.
        #     srun --exclusive --export=ALL -N 1 -n 1 -w $node $COMMAND
        # fi
        # # ret=$?
        # # if [ "$ret" -gt 0 ]; then
        # #     echo "[Error: $ret] It has not been possible to run a $SERVER_NAME server on $node, please verify the configuration file and logs."
        # #     # StopServers $SERVER_NAME $hosts
        # #     exit 1
        # # fi
        # echo "[OK] $SERVER_NAME $SERVER_ID server has been stopped in node $node"
        # i=$((i+1))
        # SERVER_NUMBER=$SERVER_ID
        ACTION="down"
        FILE="./tmp/$SERVER_TYPE-hercules-$((data2stop_index_arr[$SERVER_ID]-1))-$ACTION"
        ## Checks if the file exists.
        until [ -f $FILE ]; do
            # echo "Waiting for $FILE, attemp $i"
            i=$(($i + 1))
            ## Waits "attemps" times, then an error is return.
            if [ $i -gt $ATTEMPS ]; then
                exit 1
            fi
            t=$(($i % 5))
            if [ $t -eq 0 ]; then
                echo "[+][$HOSTNAME] Waiting for server $((data2stop_index_arr[$SERVER_ID]-1)), $FILE"
            fi
            sleep 1
        done

        # ## Checks if the server was deploy correctly.
        # STATUS=$(cat $FILE | grep "STATUS" | awk '{print $3}')
        # if [ "$STATUS" != "OK" ]; then
        #     # echo "[X] Error deploying server $SERVER_NUMBER."
        #     exit 1
        # fi
        SERVER_ID=$((SERVER_ID+1))
    done
}

## To wait until all the servers are up.
WaitForServers() {
    i=0
    # get server name by arguments.
    SERVER_NAME=$1
    shift
    # get server type by arguments.
    SERVER_TYPE=$1
    shift
    hosts=("$@")
    # echo "hostnames=${hosts[@]}"
    for node in "${hosts[@]}"
    do
        COMMAND="$HERCULES_BASH_PATH/check-servers.sh $SERVER_TYPE $i start"
        echo "[+] Running comprobation $i in $node... $COMMAND"
        # if slurm is not available.
        if [[ "$SLURM" -eq "0" ]]; then
            if [ -z "$(ssh-keygen -F $node)" ]; then
                ssh-keyscan -H $node >> ~/.ssh/known_hosts
            fi
            ssh $node "$COMMAND"
        else # if slurm is available.
            srun --exclusive --export=ALL -N 1 -n 1 -w $node $COMMAND
        fi
        ret=$?
        if [ "$ret" -gt 0 ]; then
            echo "[Error: $ret] It has not been possible to run a $SERVER_NAME server on $node, please verify the configuration file and logs."
            StopServers $SERVER_NAME $hosts
            exit 1
        fi
        echo "[OK] $SERVER_NAME $i server running in $node"
        i=$((i+1))
    done
}

STATUS=$1
shift
if [[ $STATUS != "stop" && $STATUS != "start" && $STATUS != "remove" && $STATUS != "add" ]]; then
    echo "Incorrect argument in STATUS option, usage: hercules <start|stop>"
    exit 1
fi

## Check if user pass arguments.
while getopts :m:d:o:c:s:f:k:w: flag
do
    # echo "Entra en getopts"
    case "${flag}" in
        m) META_SERVER_FILE=${OPTARG};;
        d) DATA_SERVER_FILE=${OPTARG};;
        c) HERCULES_MPI_HOSTFILE_NAME=${OPTARG};;
        # Indicates whether slurm should be used when it is installed.
        s) SLURM_OPTION=${OPTARG};;
        # Configuration file path.
        f) FILE=${OPTARG};;
        # 1 to indicate that the metadata server should not be stopped.
        k) KEEP_METADATA_ALIVE_OPTION=1;;
        w) WAIT_SERVERS=${OPTARG};;
    esac
done


SLURM=-1
# If slurm option is set by the user (optional).
if [[ ! -z "$SLURM_OPTION" ]]; then
    case $SLURM_OPTION in
        0) 
            SLURM=0
        ;; 
        1) 
            SLURM=1
        ;;
        *)
            echo "Incorrect argument in SLURM option: -s <0|1>"
            exit 1
    esac
fi


KEEP_METADATA_ALIVE=0 # default value.
# If "keep alive" option is set by the user (optional).
if [[ ! -z "$KEEP_METADATA_ALIVE_OPTION" ]]; then
    case "$KEEP_METADATA_ALIVE_OPTION" in
        "0") 
        # metadata server will be stopped.
        KEEP_METADATA_ALIVE=0
        ;; 
        "1") 
        # metadata server will not be stopped.
        KEEP_METADATA_ALIVE=1
        ;;
        *)
            echo "Incorrect argument in KEEP_METADATA_ALIVE option: -k <0|1>"
            exit 1
    esac
fi
# echo "KEEP_METADATA_ALIVE_OPTION=$KEEP_METADATA_ALIVE_OPTION"


# if [[ "$SLURM" -eq "-1" && $HOSTFILES_OPTION -eq "-1" ]]; then
# if slurm option is not set by the user, we check if it is installed.
if [[ "$SLURM" -eq "-1" ]]; then
    ## If not slurm option set by user and hostnames were not specify.
    ## Verify if slurm is installed by using the env variable.
    SLURM=$([ -z "$SLURM_CLUSTER_NAME" ] && echo 0 || echo 1)
#elif [[ "$SLURM" -eq "1" && $HOSTFILES_OPTION -eq "1" ]]; then
    ## If slurm option set by user and hostnames were specify. 
#    echo "Inconsistency found, SLURM option (-s 1) and hostfiles (-m, -d, -c) could not be used together. Set "-s 0" or remove hostfile options."
fi

# If slurm is not use, we hope user set three hostfiles (for metadata, data and clients).
SERVERS_HOSTFILES_OPTION=0
if [[ "$SLURM" -eq "0" && ! $STATUS = "stop" ]]; then
    if [ ! -z "$DATA_SERVER_FILE" ]; then
        echo "Data server file - $DATA_SERVER_FILE"
        if [ ! -f "$DATA_SERVER_FILE" ]; then
            echo "Data server file " $DATA_SERVER_FILE " does not exists"
            exit 0
        fi
        # HOSTFILES_OPTION=1
        SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
    fi
    if [ ! -z "$META_SERVER_FILE" ]; then
        echo "Meta server file - $META_SERVER_FILE"
        if [ ! -f "$META_SERVER_FILE" ]; then
            echo "Meta server file " $META_SERVER_FILE " does not exists"
            exit 0
        fi
        # SERVERS_HOSTFILES_OPTION=1
        SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
    fi
    # client hostfile is optional.
    if [ ! -z "$HERCULES_MPI_HOSTFILE_NAME" ]; then
        echo "Client file - $HERCULES_MPI_HOSTFILE_NAME"
        if [ ! -f "$HERCULES_MPI_HOSTFILE_NAME" ]; then
            echo "Client deployment file " $HERCULES_MPI_HOSTFILE_NAME " does not exists"
            exit 0
        fi
        # SERVERS_HOSTFILES_OPTION=1
        #SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
    fi
    # if a server hostfile is missing. 
    if [  ! "$SERVERS_HOSTFILES_OPTION" -eq "2" ]; then
        echo "One or more hostfiles missing for the servers, please specify them with: -m <metadata_hostfile> -d <data_hostfile>"
        exit 0
    fi
fi

if [ ! "$SLURM" -eq "-1" ]; then
    echo "SLURM - $SLURM"
fi

if [ ! -z "$STATUS" ]; then
    echo "STATUS - $STATUS"
fi

if [ ! -z "$FILE" ]; then ## Checks if a configuration file was provided by the user.
    if [ ! -f "$FILE" ]; then ## Verify if that configuration file exists.
        echo "Configuration file " $FILE " does not exists"
        exit 0
    else
        ## To get absolute path of the configuration file.
        ## To know if realpath is available.
        realpath "$FILE" 2> /dev/null
        if [ $? -eq 127 ]; then ## realpath is not available.
            echo ""
        else ## realpath is available
            FILE=$(realpath $FILE)
        fi
    fi
fi


## Define values.
## If a configuration file was not provided.
if [ -z "$FILE" ]; then
    ## To know if a configuration file exists in the default paths.
    for FILE in {"/etc/hercules.conf","./hercules.conf","hercules.conf","../conf/hercules.conf"}
    do
        echo "Checking configuration file - " $FILE
        if [ -f "$FILE" ]; then
            break
        fi
        FILE=""
    done
fi

if [ -z "$FILE" ]; then
    echo "No configuration file was provided. Please create one and specify it using -f <file_path>"
    exit 1
fi

echo "Reading configuration from $FILE"
export HERCULES_CONF="$FILE"


## checks if a configuration file was set.
if [ -z "$FILE" ]; then
    ## get current directory has project path.
    HERCULES_PATH=$(dirname `pwd`)
else
    ## get the project path from the configuration file.
    HERCULES_PATH=$(cat "$FILE" | grep "HERCULES_PATH" | awk '{print $3}')
fi

if [ ! -e "$HERCULES_PATH" ]; then
    echo "$HERCULES_PATH does not exist, please check the configuration file: $FILE"
fi

## The next line returns 1 if hercules has been loaded by using spack, 0 in other case.
IS_SPACK=$([ -z $(whereis hercules | awk '{print $2}') ] && echo 0 || echo 1)
#echo "IS_SPACK=$IS_SPACK"
# Paths may vary between spack and git.
if [[ "$IS_SPACK" -eq "1" ]]; then
    echo "Hercules has been loaded with Spack"
    # following line does not work for all spack versions.
    #HERCULES_PATH=$(spack find --paths --loaded hercules | grep hercules | awk '{print $2}') 
    HERCULES_BUILD_PATH=$HERCULES_PATH/bin
    HERCULES_BASH_PATH=$HERCULES_PATH/bin
    HERCULES_POSIX_PRELOAD="$HERCULES_PATH/lib/libhercules_posix.so"
else
    HERCULES_BUILD_PATH=$HERCULES_PATH/build
    HERCULES_BASH_PATH=$HERCULES_PATH/scripts
    HERCULES_POSIX_PRELOAD="$HERCULES_PATH/build/tools/libhercules_posix.so"
fi

export HERCULES_PATH=$HERCULES_PATH
echo "Hercules path - $HERCULES_PATH"


## Read configuration file.
export HERCULES_MOUNT_POINT=$(cat $FILE | grep "MOUNT_POINT" | head -1 | awk '{print $3}')
META_PORT=$(cat $FILE | grep "METADATA_PORT" | awk '{print $3}')
DATA_PORT=$(cat $FILE | grep "DATA_PORT" | awk '{print $3}')
MALLEABILITY=$(cat $FILE | grep "MALLEABILITY" | awk '{print $3}')
HERCULES_NUM_METADATA=$(cat $FILE | grep "NUM_META_SERVERS" | awk '{print $3}')
export HERCULES_NUM_DATA=$(cat $FILE | grep "NUM_DATA_SERVERS" | awk '{print $3}')
NUM_NODES_FOR_CLIENTS=$(cat $FILE | grep "NUM_NODES_FOR_CLIENTS" | awk '{print $3}')
NUM_CLIENTS_PER_NODE=$(cat $FILE | grep "NUM_CLIENTS_PER_NODE" | awk '{print $3}')
ATTACHED=$(cat $FILE | grep "ATTACHED" | awk '{print $3}')
HERCULES_BLOCK_SIZE=$(cat $FILE | grep "BLOCK_SIZE" | awk '{print $3}')
STORAGE_SIZE=$(cat $FILE | grep "STORAGE_SIZE" | awk '{print $3}')
HERCULES_DATA_HOSTFILE=$(cat $FILE | grep "\<DATA_HOSTFILE\>" | awk '{print $3}')
HERCULES_METADATA_HOSTFILE=$(cat $FILE | grep "METADATA_HOSTFILE" | awk '{print $3}')

## \< \> to match exact word.

## Checks if the user wants to stop the services.
if [[ $STATUS = "stop" ]];
then
    ## Stops data and metadata servers.

    # Checks if a list of data servers was passed by the user.
    # If the user does not pass any list, all dataservers will be 
    # stopped.
    if [ ! -z "$DATA_SERVER_FILE" ]; then
        echo "Data server file - $DATA_SERVER_FILE"
        if [ ! -f "$DATA_SERVER_FILE" ]; then
            echo "Data server file " $DATA_SERVER_FILE " does not exists"
            exit 0
        fi
        HERCULES_DATA_HOSTFILE=$DATA_SERVER_FILE
    fi
    readarray -t hosts < $HERCULES_DATA_HOSTFILE
    # echo "data hosts=$hosts"
    StopServers "data" $hosts $WAIT_SERVERS
    
    # Checks if user do not want to stop metadata server (KEEP_METADATA_ALIVE==1).
    ## echo "KEEP_METADATA_ALIVE=$KEEP_METADATA_ALIVE"
    if [ "$KEEP_METADATA_ALIVE" -eq "1" ]; then
        exit 0
    fi
    # Stop metadata servers.
    readarray -t hosts < $HERCULES_METADATA_HOSTFILE
    # echo "meta hosts=$hosts"
    StopServers "metadata" $hosts $WAIT_SERVERS
    # fi
    exit 0
fi

## Checks if the user wants to add more servers.
# if [[ $STATUS = "add" ]];
# then
    

# fi

## If hostfiles was not set, then we create a hostfile containing the allocated nodes.
# if [[ $SLURM -eq "1" ]]; then
echo "SERVERS_HOSTFILES_OPTION=$SERVERS_HOSTFILES_OPTION"
if [[ $SERVERS_HOSTFILES_OPTION -eq "0" ]]; then
    #srun -pernode hostname |sort > hostfile
    scontrol show hostnames "$SLURM_JOB_NODELIST" > hostfile
    # scontrol show hostnames "$SLURM_JOB_NODELIST"
fi

# exit 0

echo HERCULES_MOUNT_POINT - "$HERCULES_MOUNT_POINT" - HERCULES_BLOCK_SIZE - "$HERCULES_BLOCK_SIZE"


# If a client hostfile was not provided we set a default path.
if [ -z "$HERCULES_MPI_HOSTFILE_NAME" ]; then
    ## Warning if slurm is not being used and no client hostfile was defined.
    if [[ $SLURM -eq "0" ]]; then
    # if [[ $HOSTFILES_OPTION -eq "-1" ]]; then
        echo "[Warning] Client hostfile not specified, you can specify it with -c <filename> flag."
        # exit 1
    fi
    ## Creates a client hostfile using some of the allocates nodes.
    if [[ $SLURM -eq "1" ]]; then
        HERCULES_MPI_HOSTFILE_NAME="client_hostfile"
        if [[ $ATTACHED -eq "1" ]]; then
            tail -n +$((HERCULES_NUM_METADATA+1)) hostfile | head -n $NUM_NODES_FOR_CLIENTS > $HERCULES_MPI_HOSTFILE_NAME
        else
            tail -n +$((HERCULES_NUM_METADATA+HERCULES_NUM_DATA+1)) hostfile | head -n $NUM_NODES_FOR_CLIENTS > $HERCULES_MPI_HOSTFILE_NAME
        fi
    fi
fi


## To run the metadata servers.
## Checks if a metadata hostfile was not defined.
if [[ -z $META_SERVER_FILE ]];
then
    ## Error if slurm is not being used and no metadata hostfile was defined.
    if [[ "$SLURM" -eq "0" ]]; then
        echo "[Error] Metadata server file not specified, please set one using -m <filename> flag."
        exit 1
    fi
    echo "[+] Metadata server file not specified, getting information from slurm."
    ## If a metadata file was not defined and we have slurm's nodes allocated,
    ## then we create a file which contains the hostnames of the nodes that
    ## will be used to deploy the determinate set of metadata servers.
    #readarray -t meta_hosts < <(head -n $HERCULES_NUM_METADATA hostfile)
    head -n "$HERCULES_NUM_METADATA" hostfile > "$HERCULES_METADATA_HOSTFILE"
    ## To create an array with the meta nodes.
    #printf "%s\n" ${meta_hosts[@]} > "$META_SERVER_FILE"
    readarray -t meta_hosts < "$HERCULES_METADATA_HOSTFILE"
else
    ## If a metadata file was defined we read it to create an array which
    ## contains the hostnames of the nodes that will be used to deploy the
    ## determinate set of metadata servers.
    echo "[+] Reading metadata server file - $META_SERVER_FILE"
    readarray -t meta_hosts < "$META_SERVER_FILE"
fi

## The array is read to deploy the metadata servers.
i=0
echo "[+] Hercules: Starting metadata servers on ${meta_hosts[@]}"
start=`date +%s.%N`
for node in ${meta_hosts[@]}
do    
    RM="rm /tmp/m-hercules-$i"
    COMMAND="$HERCULES_BUILD_PATH/hercules_server m $i"
    ## If slurm is not being used, we deploy the service by connecting
    ## to the node via ssh.
    if [[ "$SLURM" -eq "0" ]]; then
        #{ ssh $node "$RM; cd $HERCULES_BASH_PATH && $COMMAND"; } &
        echo "[ + ] Removing temporal files on $node"
        ( ssh $node "$RM" )
        echo "[ + ] Starting metadata server $i on $node..."
        ( ssh $node "cd $HERCULES_BASH_PATH && HERCULES_CONF=$FILE $COMMAND" ) &
    else
        ## Deletes the file that we use to make sure that the server has started.
        echo "[+] Removing temporal files on $node"
        srun --exclusive --export=ALL -N 1 -n 1 -w $node $RM 2> /dev/null
        ## If slurm is being used, the service is deploy using srun.
        echo "[+] Starting metadata server $i on $node..."
        srun --exclusive --export=ALL -N 1 -n 1 -w $node $COMMAND &
    fi
    i=$(($i+1))
done


## Wait until all metadata servers are up.
WaitForServers "metadata" "m" ${meta_hosts[@]}
end=`date +%s.%N`
runtime=$( echo "$end - $start" | bc -l )
echo "[-] Metadata servers started in $runtime seconds"

## To run the data servers.
if [[ -z $DATA_SERVER_FILE ]];
then
    ## Error if slurm is not being used and no data hostfile was defined.
    if [[ "$SLURM" -eq "0" ]]; then
        echo "[Error] Data server file not specified, please set one using -d <filename> flag."
        exit 1
    fi
    echo "[+] Data server file not specified, getting information from slurm."
    ## If a data file was not defined and we have slurm's nodes allocated,
    ## then we create a file which contains the hostnames of the nodes that
    ## will be used to deploy the determinate set of data servers.
    # readarray -t data_hosts < <(tail -n +$((HERCULES_NUM_METADATA+1)) hostfile | head -n $HERCULES_NUM_DATA)
    tail -n +$((HERCULES_NUM_METADATA+1)) hostfile | head -n "$HERCULES_NUM_DATA" > "$HERCULES_DATA_HOSTFILE"
    ## To create an array with the data nodes.
    # printf "%s\n" ${data_hosts[@]} > "$DATA_SERVER_FILE"
    readarray -t data_hosts < "$HERCULES_DATA_HOSTFILE"
else
    ## If a data file was defined we read it to create an array which
    ## contains the hostnames of the nodes that will be used to deploy the
    ## determinate set of data servers.
    echo "[+] Reading data server file."
    readarray -t data_hosts < "$DATA_SERVER_FILE"
fi

i=0
echo "[+] Hercules: Starting data servers on ${data_hosts[@]}"
start=`date +%s.%N`
for node in ${data_hosts[@]}
do
    # echo "[+] Running data server $i in $node..."
    RM="rm /tmp/d-hercules-$i"
    COMMAND="$HERCULES_BUILD_PATH/hercules_server d $i ${meta_hosts[0]}"
    if [[ "$SLURM" -eq "0" ]]; then
        # ssh $node "$RM; cd $HERCULES_BASH_PATH &&  $COMMAND &"
        echo "[ + ] Removing temporal files on $node"
        ( ssh $node "$RM" )
        echo "[ + ] Starting data server $i in $node..."
        ( ssh $node "cd $HERCULES_BASH_PATH && HERCULES_CONF=$FILE $COMMAND" ) &
    else
        ## Deletes the file that we use to make sure that the server has started.
        echo "[+] Removing temporal files on $node"
        srun --exclusive --export=ALL -N 1 -n 1 -w $node $RM 2> /dev/null
        ## If slurm is being used, the service is deploy using srun.
        echo "[+] Starting data server $i on $node..."
        srun --exclusive --export=ALL -N 1 -n 1 -w $node $COMMAND &
    fi
    i=$(($i+1))
done

## Wait until all data servers are up.
WaitForServers "data" "d" ${data_hosts[@]}
end=`date +%s.%N`
runtime=$( echo "$end - $start" | bc -l )
echo "[-] Data servers started in $runtime seconds"


## Search for the mpi distribution installed.
for MPI_DS in {"open-mpi","mpich","Intel"}
do
    RET=$(mpiexec --version | grep -c $MPI_DS)
    if [ $RET -gt 0 ]; then
        echo "[+] MPI distribution found; $MPI_DS"
        break;
    fi
    MPI_DS=''
done

case $MPI_DS in
    "open-mpi")
        # echo "[+] Option openmpi"
        export HERCULES_MPI_ENV_DEF="-x"
        export HERCULES_MPI_HOSTFILE_DEF="-hostfile"
        export HERCULES_MPI_PPN="--npernode"
        #export H_MPI_NNFC=""
    ;;
    "mpich" | "impi")
        # echo "[+] Option mpich | impi"
        export HERCULES_MPI_ENV_DEF="-env"
        export HERCULES_MPI_HOSTFILE_DEF="-f"
        export HERCULES_MPI_PPN="-ppn"
    ;;
    *)
        # Check!
        echo "[WARNING] No mpi distribution found"
        # exit 1
    ;;
esac

# set enviroment variables.
export HERCULES_NCPN=$NUM_CLIENTS_PER_NODE
export HERCULES_NNFC=$NUM_NODES_FOR_CLIENTS


unset META_PORT
unset DATA_PORT
unset MALLEABILITY
# unset HERCULES_NUM_METADATA
# unset HERCULES_NUM_DATA
unset NUM_NODES_FOR_CLIENTS
unset NUM_CLIENTS_PER_NODE
# unset HERCULES_BLOCK_SIZE
unset STORAGE_SIZE


# if [[ "$SLURM" -eq "0" ]]; then
    GREEN='\033[0;32m'  # Green
    RED='\033[0;31m'          # Red
    YELLOW='\033[33m'    # Yellow
    NC='\033[0m'    # No Color

    echo -e "#############################################################################
    [!] 1. To export the path of the configuration file, run the following command:
    ${GREEN}
export HERCULES_CONF=$FILE
    ${NC}
    #############################################################################"

    echo -e "#############################################################################
    [!] 2. To load the client library:
    ${GREEN}
export LD_PRELOAD=$HERCULES_POSIX_PRELOAD
    ${NC}
    #############################################################################"

    echo -e "#############################################################################
    [!] 2. To unload the client library:
    ${RED}
unset LD_PRELOAD=$HERCULES_POSIX_PRELOAD
    ${NC}
    #############################################################################"

    echo -e "#############################################################################
    [!] To stop the services:
    ${RED}
hercules stop -f $FILE
    ${NC}
    #############################################################################"

    echo -e "#############################################################################
    [!] Warning: due to UCX bug (Shared memory error) it is sometimes necesary to run:
    ${YELLOW}
export UCX_POSIX_USE_PROC_LINK=n
    ${NC}
    #############################################################################"


# fi

# export LD_PRELOAD=$HERCULES_PATH/build/tools/libhercules_posix.so
