#!/bin/bash
## Last modification: 30/01/2025
## Genaro Sanchez-Gallegos
#set -x
#######################################################
#######################################################
## To stop servers.
StopServers() {
    NAME=$1 # Server type ("metadata" or "data").
    shift
    # Operation to be apply to the server. 
    # 0 indicates the server will be killed, and 
    # 1 indicates the sever will be suspend 
    # (e.g., Hercules shrink when malleability is enabled).
    OPERATION=$1
    shift
    hosts=("$@") # List of hostnames.
 
    unset LD_PRELOAD

    echo "# Hercules: Stopping $NAME servers in ${hosts[@]}"
    if [[ "$VERBOSE" -eq "1" ]]; then
        echo "# Operation = ${OPERATION}"
    fi
    echo ${OPERATION} > "${HERCULES_PATH}/tmp/hercules_pkill_operation"

    i=0
    # Sends the pkill operation to each server.
    for node in "${hosts[@]}"
    do
        RM="rm ${HERCULES_PATH}/tmp/d-hercules-$i-stop"
        # Set the action to be doing by the servers when they received the pkill signal.
        # ( ssh $node  "echo $OPERATION > ./tmp/hercules_pkill_operation" )
        # Kill threads and finish the server.
        echo "[+] Removing temporal files on ${node}"
        ( ssh $node "$RM" )
        ( ssh ${node} "pkill -SIGUSR1 hercules_server" )
        i=$(($i+1))
    done
    rm "${HERCULES_PATH}/tmp/hercules_pkill_operation"
}

WakeUpServers() {
    NAME=$1 # Server type ("meta" or "data").
    shift
    hosts=("$@") # List of hostnames.
    # hosts=$2 # List of hostnames.

    # Wake up desired servers.
    for node in "${hosts[@]}"
    do
        ### echo "ssh $node pkill hercules_server"
        ( ssh $node "pkill -SIGUSR2 hercules_server" )
    done
    #set -x
    awk 'FNR==NR{a[$0]=NR;next}{print a[$0]}' ${HERCULES_DATA_HOSTFILE} ${HERCULES_DATA_HOSTFILE_PROV} > ${HERCULES_PATH}/tmp/data2up_index_$SLURM_JOB_ID
    #set +x
    WaitForServers "data" "d" "up" ${hosts[@]}    
}

## To wait until all the servers are up.
WaitForServers() {

    # i=0
    SERVER_ID=0

    # get server name by arguments.
    SERVER_NAME=$1
    shift
    # get server type by arguments.
    SERVER_TYPE=$1
    shift
    # get the action type.
    ACTION=$1
    shift
    # get the host list.
    hosts=("$@")

    file_name="${HERCULES_PATH}/tmp/data2${ACTION}_index_${SLURM_JOB_ID}"
    readarray -t server_index_arr < ${file_name} #data2start_index-<SLURM-JOD-ID>
    
    for node in "${hosts[@]}"
    do
        SERVER_NUMBER=$((server_index_arr[$SERVER_ID]-1))
        if [[ "$VERBOSE" -eq "1" ]]; then
            echo "# Hercules: ${ACTION} ${SERVER_NAME} server ${SERVER_NUMBER} on ${node}"
        fi
        COMMAND="${HERCULES_BASH_PATH}/check-servers.sh ${SERVER_TYPE} ${SERVER_NUMBER} ${ACTION} ${HERCULES_PATH}"
        
        # if slurm is not available.
        if [[ "$SLURM" -eq "0" ]]; then
            if [ -z "$(ssh-keygen -F $node)" ]; then
                ssh-keyscan -H $node >> ~/.ssh/known_hosts
            fi
            if [[ "$VERBOSE" -eq "1" ]]; then
                echo "Running ssh $node -- $COMMAND"
            fi
            ret=$(ssh $node -- "$COMMAND")
            if [[ "$VERBOSE" -eq "1" ]]; then
                echo "Return code $ret"
            fi
        else # if slurm is available.
        set -x
            ret=$(srun -N 1 -n 1 -c 1 -m block:block:block --mem=1G -w ${node} -- ${COMMAND})
        fi
        ret=$?
        
        if [ "$ret" -gt 0 ]; then
            echo "[Error: $ret] It has not been possible to "${ACTION}" a ${SERVER_NAME} server on ${node}, please verify the configuration file and logs."
            exit 1
        fi
        
        if [[ "$VERBOSE" -eq "1" ]]; then
            echo "[OK] ${SERVER_NAME} server ${SERVER_ID} ${ACTION} in ${node}"
        fi        
        SERVER_ID=$((SERVER_ID+1))
        set +x
    done
}

STATUS=$1
shift
if [[ $STATUS != "stop" && $STATUS != "start" && $STATUS != "remove" && $STATUS != "add" ]]; then
    echo "Incorrect argument in STATUS option, usage: hercules <start|stop>"
    exit 1
fi

WAIT_SERVERS=1
VERBOSE=0

## Check if user pass arguments.
while getopts :m:d:o:c:s:f:k:w:V: flag
do
    # echo "Entra en getopts"
    case "${flag}" in
        m) META_SERVER_FILE=${OPTARG};;
        d) DATA_SERVER_FILE=${OPTARG};;
        c) HERCULES_MPI_HOSTFILE_NAME=${OPTARG};;
        # Indicates whether slurm should be used when it is installed.
        s) SLURM_OPTION=${OPTARG};;
        # Configuration file path.
        f) FILE=${OPTARG};;
        # 1 to indicate that the metadata server should not be stopped.
        k) KEEP_METADATA_ALIVE_OPTION=1;;
        w) WAIT_SERVERS=${OPTARG};;
        V) VERBOSE=${OPTARG};;
    esac
done

# echo "Wait servers = "$WAIT_SERVERS
#exit 0

SLURM=-1
# If slurm option is set by the user (optional).
if [[ ! -z "$SLURM_OPTION" ]]; then
    case $SLURM_OPTION in
        0) 
            SLURM=0
        ;; 
        1) 
            SLURM=1
        ;;
        *)
            echo "Incorrect argument in SLURM option: -s <0|1>"
            exit 1
    esac
fi


KEEP_METADATA_ALIVE=0 # default value.
# If "keep alive" option is set by the user (optional).
if [[ ! -z "$KEEP_METADATA_ALIVE_OPTION" ]]; then
    case "$KEEP_METADATA_ALIVE_OPTION" in
        "0") 
        # metadata server will be stopped.
        KEEP_METADATA_ALIVE=0
        ;; 
        "1") 
        # metadata server will not be stopped.
        KEEP_METADATA_ALIVE=1
        ;;
        *)
            echo "Incorrect argument in KEEP_METADATA_ALIVE option: -k <0|1>"
            exit 1
    esac
fi
# echo "KEEP_METADATA_ALIVE_OPTION=$KEEP_METADATA_ALIVE_OPTION"


# if [[ "$SLURM" -eq "-1" && $HOSTFILES_OPTION -eq "-1" ]]; then
# if slurm option is not set by the user, we check if it is installed.
if [[ "$SLURM" -eq "-1" ]]; then
    ## If not slurm option set by user and hostnames were not specify.
    ## Verify if slurm is installed by using the env variable.
    SLURM=$([ -z "$SLURM_CLUSTER_NAME" ] && echo 0 || echo 1)
#elif [[ "$SLURM" -eq "1" && $HOSTFILES_OPTION -eq "1" ]]; then
    ## If slurm option set by user and hostnames were specify. 
#    echo "Inconsistency found, SLURM option (-s 1) and hostfiles (-m, -d, -c) could not be used together. Set "-s 0" or remove hostfile options."
fi

if [ ! -z "$FILE" ]; then ## Checks if a configuration file was provided by the user.
    if [ ! -f "$FILE" ]; then ## Verify if that configuration file exists.
        echo "Configuration file " $FILE " does not exists"
        exit 0
    else
        ## To get absolute path of the configuration file.
        ## To know if realpath is available.
        realpath "$FILE" 2> /dev/null
        if [ $? -eq 127 ]; then ## realpath is not available.
            echo ""
        else ## realpath is available
            FILE=$(realpath $FILE)
        fi
    fi
fi


## Define values.
## If a configuration file was not provided.
if [ -z "$FILE" ]; then
    ## To know if a configuration file exists in the default paths.
    for FILE in {"/etc/hercules.conf","./hercules.conf","hercules.conf","../conf/hercules.conf"}
    do
        echo "Checking configuration file - " $FILE
        if [ -f "$FILE" ]; then
            break
        fi
        FILE=""
    done
fi

if [ -z "$FILE" ]; then
    echo "No configuration file was provided. Please create one and specify it using -f <file_path>"
    exit 1
fi

if [[ "$VERBOSE" -eq "1" ]]; then
    echo "Reading configuration from $FILE"
fi
#export HERCULES_CONF="$FILE"


## Checks if a configuration file was set.
if [ -z "$FILE" ]; then
    ## get current directory as project path.
    HERCULES_PATH=$(dirname `pwd`)
else
    ## get the project path from the configuration file.
    HERCULES_PATH=$(cat "$FILE" | grep "HERCULES_PATH" | awk '{print $3}')
fi

if [ ! -e "$HERCULES_PATH" ]; then
    echo "$HERCULES_PATH does not exist, please check the configuration file: $FILE"
fi

# If slurm is not use, we hope user set three hostfiles (for metadata, data and clients).
SERVERS_HOSTFILES_OPTION=0
if [[ "$SLURM" -eq "0" && ! $STATUS = "stop" ]]; then
    if [ ! -z "$DATA_SERVER_FILE" ]; then
        echo "Data server file - $DATA_SERVER_FILE"
        if [ ! -f "$DATA_SERVER_FILE" ]; then
            echo "Data server file " $DATA_SERVER_FILE " does not exists"
            exit 0
        fi
        # HOSTFILES_OPTION=1
        SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
    fi
    if [ ! -z "$META_SERVER_FILE" ]; then
        echo "Meta server file - $META_SERVER_FILE"
        if [ ! -f "$META_SERVER_FILE" ]; then
            echo "Meta server file " $META_SERVER_FILE " does not exists"
            exit 0
        fi
        # SERVERS_HOSTFILES_OPTION=1
        SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
    fi
    # client hostfile is optional.
    if [ ! -z "$HERCULES_MPI_HOSTFILE_NAME" ]; then
        echo "Client file - $HERCULES_MPI_HOSTFILE_NAME"
        if [ ! -f "$HERCULES_MPI_HOSTFILE_NAME" ]; then
            echo "Client deployment file " $HERCULES_MPI_HOSTFILE_NAME " does not exists"
            exit 0
        fi
        # SERVERS_HOSTFILES_OPTION=1
        #SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
    fi
fi


## The next line returns 1 if hercules has been loaded by using spack, 0 in other case.
IS_SPACK=$([ -z $(whereis '\<hercules\>' | awk '{print $2}') ] && echo 0 || echo 1)
#echo "IS_SPACK=$IS_SPACK"
# Paths may vary between spack and git.
if [[ "$IS_SPACK" -eq "1" ]]; then
    if [[ "$VERBOSE" -eq "1" ]]; then
        echo "Hercules has been loaded with Spack"
    fi
    # following line does not work for all spack versions.
    #HERCULES_PATH=$(spack find --paths --loaded hercules | grep hercules | awk '{print $2}') 
    HERCULES_BUILD_PATH=$HERCULES_PATH/bin
    HERCULES_BASH_PATH=$HERCULES_PATH/bin
    HERCULES_POSIX_PRELOAD="$HERCULES_PATH/lib/libhercules_posix.so"
else
    HERCULES_BUILD_PATH=$HERCULES_PATH/build
    HERCULES_BASH_PATH=$HERCULES_PATH/scripts
    HERCULES_POSIX_PRELOAD="$HERCULES_PATH/build/tools/libhercules_posix.so"
fi

export HERCULES_PATH=$HERCULES_PATH
if [[ "$VERBOSE" -eq "1" ]]; then
    echo "Hercules path - $HERCULES_PATH"
fi

## Read configuration file.
export HERCULES_MOUNT_POINT=$(cat $FILE | grep "\<MOUNT_POINT\>" | head -1 | awk '{print $3}')
META_PORT=$(cat $FILE | grep "\<METADATA_PORT\>" | awk '{print $3}')
DATA_PORT=$(cat $FILE | grep "\<DATA_PORT\>" | awk '{print $3}')
MALLEABILITY=$(cat $FILE | grep "\<MALLEABILITY\>" | awk '{print $3}')
HERCULES_NUM_METADATA=$(cat $FILE | grep "\<NUM_META_SERVERS\>" | awk '{print $3}')
export HERCULES_NUM_DATA=$(cat $FILE | grep "\<NUM_DATA_SERVERS\>" | awk '{print $3}')
NUM_NODES_FOR_CLIENTS=$(cat $FILE | grep "\<NUM_NODES_FOR_CLIENTS\>" | awk '{print $3}')
NUM_CLIENTS_PER_NODE=$(cat $FILE | grep "\<NUM_CLIENTS_PER_NODE\>" | awk '{print $3}')
ATTACHED=$(cat $FILE | grep "\<ATTACHED\>" | awk '{print $3}')
HERCULES_BLOCK_SIZE=$(cat $FILE | grep "\<BLOCK_SIZE\>" | awk '{print $3}')
STORAGE_SIZE=$(cat $FILE | grep "\<STORAGE_SIZE\>" | awk '{print $3}')
HERCULES_DATA_HOSTFILE=$(cat $FILE | grep "\<DATA_HOSTFILE\>" | awk '{print $3}')
HERCULES_METADATA_HOSTFILE=$(cat $FILE | grep "\<METADATA_HOSTFILE\>" | awk '{print $3}')
INIT_HERCULES_NUM_DATA=$(cat $FILE | grep "\<INIT_NUM_DATA_SERVERS\>" | awk '{print $3}')

if [ -z "$INIT_HERCULES_NUM_DATA" ] || [ "$INIT_HERCULES_NUM_DATA" = "0" ] ; then
    INIT_HERCULES_NUM_DATA=$HERCULES_NUM_DATA
    echo "INIT_HERCULES_NUM_DATA = $INIT_HERCULES_NUM_DATA"
fi

# set -x
if [[ "$SLURM" -eq "1" ]]; then
    echo "[+] Slurm is active."
    ## If slurm is enabled, we concat the job id to the configuration file to create a new one.
    CURR_HERCULES_CONF_FILE="${FILE}_${SLURM_JOB_ID}"
    cp "${FILE}" "${CURR_HERCULES_CONF_FILE}"
else 
    CURR_HERCULES_CONF_FILE="${FILE}"
fi

export HERCULES_CONF="${CURR_HERCULES_CONF_FILE}"
# exit 0

# echo "+ + + Initial number of data nodes is $INIT_HERCULES_NUM_DATA/$HERCULES_NUM_DATA"
export HERCULES_INIT_NUM_DATA="${INIT_HERCULES_NUM_DATA}"

## \< \> to match exact word.

## Checks if the user wants to stop the services.
if [[ $STATUS = "stop" ]];
then
    ## Stops data and metadata servers.
 
    # Checks if a list of data servers was passed by the user.
    # If the user does not pass any list, all dataservers will be 
    # stopped.
    if [ ! -z "$DATA_SERVER_FILE" ]; then
        # echo "Data server file - $DATA_SERVER_FILE"
        if [ ! -f "$DATA_SERVER_FILE" ]; then
            echo "Data server file " $DATA_SERVER_FILE " does not exists"
            exit 0
        fi
        HERCULES_DATA_HOSTFILE=$DATA_SERVER_FILE
    fi

    ## Write the default file "data2stop_hostfile".
    ## To avoid overwrite this file, user must to use 
    ## the hercules "remove" option to stop only some
    ## data servers. "stop" option will stop all running
    ## data servers.
    cat $HERCULES_DATA_HOSTFILE > "${HERCULES_PATH}/tmp/data2stop_hostfile_$SLURM_JOB_ID"

    ## Creates an array with the data servers hostnames.
    readarray -t hosts < $HERCULES_DATA_HOSTFILE
    ## Stop the data servers.
    ## TODO: check if the servers are running on the remote node
    ## before to try stop them.
    StopServers "data" 1 ${hosts[@]}
    
    ## Checks if user wants to wait until all servers are stopped.
    # 1 indicates that this function should check if 
    # all servers have stopped correctly (synchronous).
    # 0 in other case (asynchronous).
    if [[ "$WAIT_SERVERS" -eq "1" ]]; then
        set -x
        awk 'FNR==NR{a[$0]=NR;next}{print a[$0]}' ${HERCULES_DATA_HOSTFILE} ${HERCULES_DATA_HOSTFILE} > "${HERCULES_PATH}/tmp/data2${STATUS}_index_$SLURM_JOB_ID"
        set +x
        WaitForServers "data" "d" "${STATUS}" ${hosts[@]}
    else
        echo "No waiting for data servers to be stopped."
    fi
    
    # Checks if user do not want to stop metadata server (KEEP_METADATA_ALIVE==1).
    ## echo "KEEP_METADATA_ALIVE=$KEEP_METADATA_ALIVE"
    if [ "$KEEP_METADATA_ALIVE" -eq "1" ]; then
        exit 0
    fi
    # Stop metadata servers.
    cat $HERCULES_METADATA_HOSTFILE > "${HERCULES_PATH}/tmp/data2stop_hostfile_$SLURM_JOB_ID"
    readarray -t hosts < $HERCULES_METADATA_HOSTFILE
    # echo "meta hosts=$hosts"
    StopServers "metadata" 1 ${hosts[@]}

    ## Checks if user wants to wait until all servers are stopped.
    # 1 indicates that this function should check if 
    # all servers have stopped correctly (synchronous).
    # 0 in other case (asynchronous).
    if [[ "$WAIT_SERVERS" -eq "1" ]]; then
        set -x
        awk 'FNR==NR{a[$0]=NR;next}{print a[$0]}' ${HERCULES_METADATA_HOSTFILE} ${DATA_SERVER_FILE} > "${HERCULES_PATH}/tmp/data2${STATUS}_index"
        set +x
        WaitForServers "metadata" "m" "${STATUS}" ${hosts[@]}
    else
        echo "No waiting for data servers to be stopped."
    fi
    exit 0
fi

## Checks if the user wants to add more servers.
if [[ $STATUS = "add" ]];
then
    ## Adds data and metadata servers.
    if [[ "$VERBOSE" -eq "1" ]]; then
        echo "Starting comissioning state."
    fi
    # Checks if a list of data servers was passed by the user.
    # If the user does not pass any list, we exit the script.
    if [ ! -z "$DATA_SERVER_FILE" ]; then
        ## echo "Data server file - $DATA_SERVER_FILE"
        if [ ! -f "$DATA_SERVER_FILE" ]; then
            echo "Data server file " $DATA_SERVER_FILE " does not exists"
            exit 0
        fi
        HERCULES_DATA_HOSTFILE_PROV=$DATA_SERVER_FILE
    else 
        echo "No data server file was provided to add more servers."
        exit 0
    fi
    readarray -t hosts < $HERCULES_DATA_HOSTFILE_PROV
    # echo "data hosts=$hosts"
    WakeUpServers "data" ${hosts[@]}
    # sleep 10
    exit 0
fi

## Checks if the user wants to remove servers.
## TO FIX!!
if [[ $STATUS = "remove" ]];
then
    ## Remove data and metadata servers.
    if [[ "$VERBOSE" -eq "1" ]]; then
        echo "Starting decomissioning state."
    fi
    # Checks if a list of data servers was passed by the user.
    if [ ! -z "$DATA_SERVER_FILE" ]; then
        ## echo "Data server file - $DATA_SERVER_FILE"
        if [ ! -f "$DATA_SERVER_FILE" ]; then
            echo "Data server file " $DATA_SERVER_FILE " does not exists"
            exit 0
        fi
        # HERCULES_DATA_HOSTFILE=$DATA_SERVER_FILE
    else
        echo "Data server file is nedeed, -f <data_server_file_path>"
        exit 0
    fi
    readarray -t hosts < ${DATA_SERVER_FILE}
    # 1 = Stops some servers synchronously.
    # 0 = Do not kill the process.
    StopServers "data" 0 ${hosts[@]} 

    # For "remove" operations we awalys wait for selected 
    # servers to be removed.
    awk 'FNR==NR{a[$0]=NR;next}{print a[$0]}' ${HERCULES_DATA_HOSTFILE} ${DATA_SERVER_FILE} > "${HERCULES_PATH}/tmp/data2${STATUS}_index_$SLURM_JOB_ID"
    
    WaitForServers "data" "d" "${STATUS}" ${hosts[@]}

    # Metadata server is not stopped.
   
    exit 0
fi
# set -x
## If not empty, the field "METADATA_HOSTFILE" and "DATA_HOSTFILE" field was set on the configuration file.
if [ ! -z "$HERCULES_METADATA_HOSTFILE" ]; then
    echo "${HERCULES_METADATA_HOSTFILE} exists"
    if [[ "$SLURM" -eq "1" ]]; then
        # If slurm is enabled, we added the slurm job id to the meta hostfile.
        HERCULES_METADATA_HOSTFILE+="_"$SLURM_JOB_ID
        ## Replace all "/" with "\/" because "/" is an special character for the sed command.
        ESCAPED_HERCULES_METADATA_HOSTFILE="${HERCULES_METADATA_HOSTFILE//\//\\/}"
        ## Replace the old metadata hostfile name with the new one containing the job id.
        sed -i "s/^METADATA_HOSTFILE = .*/METADATA_HOSTFILE = $ESCAPED_HERCULES_METADATA_HOSTFILE/g"  "$CURR_HERCULES_CONF_FILE"
        # echo "HERCULES_METADATA_HOSTFILE=${HERCULES_METADATA_HOSTFILE}"
    fi
fi
if [ ! -z "${HERCULES_DATA_HOSTFILE}" ]; then
    if [[ "$SLURM" -eq "1" ]]; then
        # If slurm is enabled, we added the slurm job id to the data hostfile.
        HERCULES_DATA_HOSTFILE+="_${SLURM_JOB_ID}"
        ## Replace all "/" with "\/" because "/" is an special character for the sed command.
        ESCAPED_HERCULES_DATA_HOSTFILE="${HERCULES_DATA_HOSTFILE//\//\\/}"
        ## Replace the old data hostfile name with the new one containing the job id.
        sed -i "s/^DATA_HOSTFILE = .*/DATA_HOSTFILE = ${ESCAPED_HERCULES_DATA_HOSTFILE}/g"  "${CURR_HERCULES_CONF_FILE}"
    fi
fi
# set +x

## Creates the initial "hercules_num_act_nodes" file.
echo ${HERCULES_INIT_NUM_DATA} > ${HERCULES_PATH}/tmp/hercules_num_act_nodes

## Set the name that will be used to create the 
if [[ "$SLURM" -eq "1" ]]; then
    FULL_HOSTFILE="hostfile_$SLURM_JOB_ID"
else
    FULL_HOSTFILE="hostfile"
fi 

## If hostfiles was not set, then we create a hostfile containing the allocated nodes.
if [[ "$VERBOSE" -eq "1" ]]; then
    echo "SERVERS_HOSTFILES_OPTION=$SERVERS_HOSTFILES_OPTION"
fi
if [[ $SERVERS_HOSTFILES_OPTION -eq "0" ]]; then
    #srun -pernode hostname |sort > hostfile
    scontrol show hostnames "${SLURM_JOB_NODELIST}" > ${FULL_HOSTFILE}
    # scontrol show hostnames "$SLURM_JOB_NODELIST"
fi

echo HERCULES_MOUNT_POINT - "${HERCULES_MOUNT_POINT}" - HERCULES_BLOCK_SIZE - "${HERCULES_BLOCK_SIZE}"

# If a client hostfile was not provided we set a default path.
if [ -z "${HERCULES_MPI_HOSTFILE_NAME}" ]; then
    ## Warning if slurm is not being used and no client hostfile was defined.
    if [[ $SLURM -eq "0" ]]; then
    # if [[ $HOSTFILES_OPTION -eq "-1" ]]; then
        echo "[Warning] Client hostfile not specified, you can specify it with -c <filename> flag."
        # exit 1
    fi
    ## Creates a client hostfile using some of the allocates nodes.
    if [[ $SLURM -eq "1" ]]; then
        HERCULES_MPI_HOSTFILE_NAME="client_hostfile_"$SLURM_JOB_ID
        if [[ $ATTACHED -eq "1" ]]; then
            tail -n +$((HERCULES_NUM_METADATA+1)) $FULL_HOSTFILE | head -n $NUM_NODES_FOR_CLIENTS > $HERCULES_MPI_HOSTFILE_NAME
        else
            tail -n +$((HERCULES_NUM_METADATA+HERCULES_NUM_DATA+1)) $FULL_HOSTFILE | head -n $NUM_NODES_FOR_CLIENTS > $HERCULES_MPI_HOSTFILE_NAME
        fi
    fi
fi


## To run the metadata servers.
## Checks if a metadata hostfile was not defined.
if [[ -z $META_SERVER_FILE ]];
then
    ## If slurm is not being used and no metadata hostfile was defined
    ## we checked the configuration file path.
    if [[ "$SLURM" -eq "0" ]]; then
        ## If the path specified on the configuration file does not exist 
        ## there is an error.
        if [[ -z $HERCULES_METADATA_HOSTFILE ]];
        then
            echo "[Error] Metadata server file not specified, please set one using -m <filename> flag."
            exit 1
        fi

    else
        if [[ "$VERBOSE" -eq "1" ]]; then
            echo "[+] Metadata server file not specified, getting information from slurm."
        fi
        ## If a metadata file was not defined and we have slurm's nodes allocated,
        ## then we create a file which contains the hostnames of the nodes that
        ## will be used to deploy the determinate set of metadata servers.
        #readarray -t meta_hosts < <(head -n $HERCULES_NUM_METADATA hostfile)
        head -n "$HERCULES_NUM_METADATA" $FULL_HOSTFILE > "$HERCULES_METADATA_HOSTFILE"
    fi
    ## To create an array with the meta nodes.
    #printf "%s\n" ${meta_hosts[@]} > "$META_SERVER_FILE"
    readarray -t meta_hosts < "$HERCULES_METADATA_HOSTFILE"
else
    ## If a metadata file was defined we read it to create an array which
    ## contains the hostnames of the nodes that will be used to deploy the
    ## determinate set of metadata servers.
    echo "[+] Reading metadata server file - $META_SERVER_FILE"
    readarray -t meta_hosts < "$META_SERVER_FILE"
fi

## The array is read to deploy the metadata servers.
i=0
echo "[+] Hercules: Starting metadata servers on ${meta_hosts[@]}"
start=`date +%s.%N`
for node in ${meta_hosts[@]}
do    
    RM="rm ${HERCULES_PATH}/tmp/m-hercules-$i"
    COMMAND="${HERCULES_BUILD_PATH}/hercules_server m ${i}"
    ## If slurm is not being used, we deploy the service by connecting
    ## to the node via ssh.
    if [[ "$SLURM" -eq "0" ]]; then
        #{ ssh $node "$RM; cd $HERCULES_BASH_PATH && $COMMAND"; } &
        if [[ "$VERBOSE" -eq "1" ]]; then
            echo "[ + ] Removing temporal files on $node"
        fi
        ( ssh $node "$RM" )
        if [[ "$VERBOSE" -eq "1" ]]; then
            echo "[ + ] Starting metadata server $i on $node..."
            echo "Running ssh $node cd $HERCULES_BASH_PATH && HERCULES_CONF=$FILE $COMMAND"
        fi
        ( ssh $node "cd $HERCULES_BASH_PATH && HERCULES_CONF=$FILE $COMMAND" ) &
    else
        ## Deletes the file that we use to make sure that the server has started.
        if [[ "$VERBOSE" -eq "1" ]]; then
            echo "[+] Removing temporal files on ${node}"
        fi
        set -x
        srun -N 1 -n 1 -c 1 -m block:block:block --mem=1G -w ${node} ${RM} 2> /dev/null
        ## If slurm is being used, the service is deploy using srun.
        echo "[+] Starting metadata server $i on $node..."
        srun -N 1 -n 1 -c 1 -m block:block:block --mem=0G -w $node $COMMAND &
        set +x
    fi
    i=$(($i+1))
done


## Wait until all metadata servers are up.
awk 'FNR==NR{a[$0]=NR;next}{print a[$0]}' "${HERCULES_METADATA_HOSTFILE}" "${HERCULES_METADATA_HOSTFILE}" > "${HERCULES_PATH}/tmp/data2start_index_${SLURM_JOB_ID}"
WaitForServers "metadata" "m" "start" ${meta_hosts[@]}
end=`date +%s.%N`
runtime=$( echo "$end - $start" | bc -l )
if [[ "$VERBOSE" -eq "1" ]]; then
    echo "[-] Metadata servers started in $runtime seconds"
fi 

## To run the data servers.
if [[ -z $DATA_SERVER_FILE ]];
then
    ## If slurm is not being used and no metadata hostfile was defined
    ## we checked the configuration file path.
    if [[ "$SLURM" -eq "0" ]]; then
        ## If the path specified on the configuration file does not exist 
        ## there is an error.
        if [[ -z $HERCULES_DATA_HOSTFILE ]];
        then
            echo "[Error] Data server file not specified, please set one using -d <filename> flag."
            exit 1
        fi
    else
        if [[ "$VERBOSE" -eq "1" ]]; then
            echo "[+] Data server file not specified, getting information from slurm."
        fi
        ## If a data file was not defined and we have slurm's nodes allocated,
        ## then we create a file which contains the hostnames of the nodes that
        ## will be used to deploy the determinate set of data servers.
        # readarray -t data_hosts < <(tail -n +$((HERCULES_NUM_METADATA+1)) hostfile | head -n $HERCULES_NUM_DATA)
        tail -n +$((HERCULES_NUM_METADATA+1)) $FULL_HOSTFILE | head -n "$HERCULES_NUM_DATA" > "$HERCULES_DATA_HOSTFILE"
    fi
    ## To create an array with the data nodes.
    # printf "%s\n" ${data_hosts[@]} > "$DATA_SERVER_FILE"
    readarray -t data_hosts < "$HERCULES_DATA_HOSTFILE"
else
    ## If a data file was defined we read it to create an array which
    ## contains the hostnames of the nodes that will be used to deploy the
    ## determinate set of data servers.
    echo "[+] Reading data server file."
    readarray -t data_hosts < "$DATA_SERVER_FILE"
fi

i=0
if [[ "$VERBOSE" -eq "1" ]]; then
    echo "[+] Hercules: Starting data servers on ${data_hosts[@]}"
fi
start=`date +%s.%N`
for node in ${data_hosts[@]}
do
    RM="rm ${HERCULES_PATH}/tmp/d-hercules-$i-start"
    COMMAND="$HERCULES_BUILD_PATH/hercules_server d $i ${meta_hosts[0]} $INIT_HERCULES_NUM_DATA"
    if [[ "$SLURM" -eq "0" ]]; then
        # ssh $node "$RM; cd $HERCULES_BASH_PATH &&  $COMMAND &"
        if [[ "$VERBOSE" -eq "1" ]]; then
            echo "[ + ] Removing temporal files on $node"
        fi
        ( ssh $node "$RM" )
        if [[ "$VERBOSE" -eq "1" ]]; then
            echo "[ + ] Starting data server $i in $node..."
            echo "Running ssh $node cd $HERCULES_BASH_PATH && HERCULES_CONF=$FILE $COMMAND"
        fi
        ( ssh $node "cd $HERCULES_BASH_PATH && HERCULES_CONF=$FILE $COMMAND" ) &
    else
        ## Deletes the file that we use to make sure that the server has started.
        if [[ "$VERBOSE" -eq "1" ]]; then
            echo "[+] Removing temporal files on $node"
        fi
        srun -N 1 -n 1 -c 1 -m block:block:block --mem=1G -w $node $RM 2> /dev/null
        ## If slurm is being used, the service is deploy using srun.
        if [[ "$VERBOSE" -eq "1" ]]; then
            echo "[+] Starting data server $i on $node..."
        fi
        srun -N 1 -n 1 -c 1 -m block:block:block --mem=0G -w $node $COMMAND &
    fi
    i=$(($i+1))
done

## Wait until all data servers are up.
awk 'FNR==NR{a[$0]=NR;next}{print a[$0]}' ${HERCULES_DATA_HOSTFILE} ${HERCULES_DATA_HOSTFILE} > "${HERCULES_PATH}/tmp/data2start_index_${SLURM_JOB_ID}"
WaitForServers "data" "d" "start" ${data_hosts[@]}
end=`date +%s.%N`
runtime=$( echo "$end - $start" | bc -l )
echo "[-] Data servers started in $runtime seconds"


## Search for the mpi distribution installed.
for MPI_DS in {"open-mpi","mpich","Intel"}
do
    RET=$(mpiexec --version | grep -c $MPI_DS)
    if [ $RET -gt 0 ]; then
        echo "[+] MPI distribution found; $MPI_DS"
        break;
    fi
    MPI_DS=''
done

case $MPI_DS in
    "open-mpi")
        # echo "[+] Option openmpi"
        export HERCULES_MPI_ENV_DEF="-x"
        export HERCULES_MPI_HOSTFILE_DEF="-hostfile"
        export HERCULES_MPI_PPN="--npernode"
        #export H_MPI_NNFC=""
    ;;
    "mpich" | "impi")
        # echo "[+] Option mpich | impi"
        export HERCULES_MPI_ENV_DEF="-env"
        export HERCULES_MPI_HOSTFILE_DEF="-f"
        export HERCULES_MPI_PPN="-ppn"
    ;;
    *)
        # Check!
        echo "[WARNING] No mpi distribution found"
        # exit 1
    ;;
esac

## set enviroment variables.
# mpi options.
export "HERCULES_NCPN=${NUM_CLIENTS_PER_NODE}"
export "HERCULES_NNFC=${NUM_NODES_FOR_CLIENTS}"
# data hostfile name.
export "HERCULES_DATA_HOSTFILE=${HERCULES_DATA_HOSTFILE}"
export "HERCULES_FULL_HOSTFILE=${FULL_HOSTFILE}"

unset META_PORT
unset DATA_PORT
unset MALLEABILITY
# unset HERCULES_NUM_METADATA
# unset HERCULES_NUM_DATA
unset NUM_NODES_FOR_CLIENTS
unset NUM_CLIENTS_PER_NODE
# unset HERCULES_BLOCK_SIZE
unset STORAGE_SIZE


# if [[ "$SLURM" -eq "0" ]]; then
    GREEN='\033[0;32m'  # Green
    RED='\033[0;31m'          # Red
    YELLOW='\033[33m'    # Yellow
    NC='\033[0m'    # No Color

    echo -e "#############################################################################
    [!] 1. To export the path of the configuration file, run the following command:
    ${GREEN}
export HERCULES_CONF=$CURR_HERCULES_CONF_FILE
    ${NC}
    #############################################################################"

    echo -e "#############################################################################
    [!] 2. To load the client library:
    ${GREEN}
export LD_PRELOAD=$HERCULES_POSIX_PRELOAD
    ${NC}
    #############################################################################"

    echo -e "#############################################################################
    [!] 2. To unload the client library:
    ${RED}
unset LD_PRELOAD=$HERCULES_POSIX_PRELOAD
    ${NC}
    #############################################################################"

    echo -e "#############################################################################
    [!] To stop the services:
    ${RED}
hercules stop -f $CURR_HERCULES_CONF_FILE
    ${NC}
    #############################################################################"

    echo -e "#############################################################################
    [!] Warning: due to UCX bug (Shared memory error) it is sometimes necesary to run:
    ${YELLOW}
export UCX_POSIX_USE_PROC_LINK=n
    ${NC}
    #############################################################################"
