# Used URI for internal items definition
URI = imss://

# Block size (in KB)
BLOCK_SIZE = 512

# Used mount point in the client side
# To work with Nek5000 we need to add the last slash (/)
MOUNT_POINT = /mnt/imss/
# MOUNT_POINT = /home/genarog/Documents/UC3M/Codes/Apps/Nek5000/run/eddy_uv
# MOUNT_POINT = /home/genarog/Documents/UC3M/Codes/UPDATED_IMSS/imss/bash

# Port listening in the metadata node service
METADATA_PORT = 75000

# Port listening in the data node service
DATA_PORT =     85000

# Total number of data nodes
NUM_DATA_SERVERS = 1

# Total number of metadadata nodes
NUM_META_SERVERS = 1

# Total number of client nodes
NUM_NODES_FOR_CLIENTS = 10 # FIX

# Total number of clients per node
NUM_CLIENTS_PER_NODE = 10 # FIX

# 1: enables malleability functions
MALLEABILITY = 0
UPPER_BOUND_MALLEABILITY = 0
LOWER_BOUND_MALLEABILITY = 0

# File containing a list of nodes serving as data nodes
DATA_HOSTFILE = data_hostfile 

# File path of the persistence metadata
### Tucan
## METADA_PERSISTENCE_FILE = /home/gsanchez/IMSS/imss/bash/metadata
### MN4
## METADA_PERSISTENCE_FILE = /home/uc3m15/uc3m15006/Hercules/imss/bash/metadata
### Unito
## METADA_PERSISTENCE_FILE = /beegfs/home/javier.garciablas/imss/bash/metadata
### Local
 METADA_PERSISTENCE_FILE = /home/genarog/Documents/UC3M/Codes/UPDATED_IMSS/imss/bash/metadata


# Number of threads attending data requests
THREAD_POOL = 1

# Maximum size used by the data nodes
STORAGE_SIZE = 0 # No limit

# Main metadata node hostname
METADATA_HOST = 

# File containing a list of nodes serving as metadata nodes
METADATA_HOSTFILE = /home/genarog/Documents/UC3M/Codes/Apps/Nek5000/run/eddy_uv/hercules/my_meta_hostfile

# Debug mode (none or all)
DEBUG_LEVEL = none
